# Generated by Django 3.2.7 on 2021-09-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='prefix',
            field=models.CharField(choices=[('Miss', 'Miss'), ('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Dr', 'Dr'), ('Ms', 'Ms')], default='', max_length=60),
        ),
    ]
